name: evently
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.12.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.3.0 
  intl: ^0.20.3
  firebase_core: ^4.13.0
  cloud_firestore: ^6.7.1
  firebase_auth: ^6.5.6
  provider: ^6.1.5+1
  fluttertoast: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^6.0.0
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
